name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable, 1.30.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: Run cargo build
        run: cargo build --release
